import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Container, Row, Col } from 'react-bootstrap'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>      
        <title>My Site - Ramon</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />

          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossOrigin="anonymous"
          />
      </Head>
      <main /*className={styles.main}*/>
        <Container fluid="md">
          <Row >
            <Col sm md={8} lg={8} /*className={styles.center}*/>
              Testing Grid Bootstrap 2...
            </Col>
            <Col sm={3} >
              Testing Grid Bootstrap 3...
            </Col>
          </Row>
        </Container>
      </main>
    </>
  )
}
